name: exercise
on: push
jobs:
  job1:
   name: Job1
   runs-on: ubuntu-latest
   steps:
     - name: Job1 Step1
       run: date
     - name: Job1 Step2
       uses: actions/checkout@v2
  job2:
   name: Job2
   runs-on: windows-latest
   steps:
     - name: Job2 Step1
       uses: actions/checkout@v2
     - name: Job2 Step2
       run: date
  job3:
   name: Job3
   runs-on: macos-latest
   steps:
     - name: Job3 Step1
       uses: actions/checkout@v2
     - name: Job3 Step2
       run: date
  job4:
   name: Job4
   runs-on: ubuntu-latest
   needs: [job1,job2,job3]
   steps:
     - name: Job4 Step1
       uses: actions/checkout@v2
     - name: Job4 Step2
       run: date