name: Python Syntax Checker
on: push
jobs:
  syntax:
   name: Syntax Checker
   steps:
   - name: Python Syntax Checker
     uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
      # You may pin to the exact commit or the version.
      # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f